title: Masamune MATSUDA's page
description: いかがお過ごしでしょうか
show_downloads: false
google_analytics:
remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme
theme: jekyll-theme-leap-day
