title: Masamune MATSUDA's page
author:
  name: Masamune Matsuda
  email: "matsuda.masamune.38a[at]st.kyoto-u.ac.jp<br>※[at]を@に変換してください"
description: いかがお過ごしでしょうか
google_analytics: UA-217177525-1

minima:
  social_links:
    github: masamunematsuda

header_pages:
  - about.md
  - gallery.md

#theme: jekyll-theme-leap-day
#theme: jekyll-theme-cayman
#theme: jekyll-theme-midnight
#theme: jekyll-theme-slate
#theme: jekyll-theme-minimal

remote_theme: jekyll/minima
#theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
