title: Masamune MATSUDA's page
description: いかがお過ごしでしょうか
show_downloads: false
google_analytics: 299439414
#remote_theme: pages-themes/leap-day@v0.2.0
#plugins:
#- jekyll-remote-theme
#theme: jekyll-theme-leap-day
#theme: jekyll-theme-cayman
#theme: jekyll-theme-midnight
#theme: jekyll-theme-slate
#theme: jekyll-theme-minimal
theme: jekyll-theme-minima