title: Masamune MATSUDA's page
author: Masamune Matsuda
email: matsuda.masamune.38a@st.kyoto-u.ac.jp
description: いかがお過ごしでしょうか
show_downloads: false
google_analytics: 299439414

minima:
  social_links:
    github: masamunematsuda

header_pages:
  - about.md
  - gallery.md

#theme: jekyll-theme-leap-day
#theme: jekyll-theme-cayman
#theme: jekyll-theme-midnight
#theme: jekyll-theme-slate
#theme: jekyll-theme-minimal
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag